logging:
  level:
    org.hibernate.SQL: debug # SQL 로그 출력을 위한 로그 레벨 조정
    com.psc.sample: debug
server:
  port: 7080
spring:
  application:
    name: oauth2
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true # SQL 로그 출력
  h2.console:
    enabled: true # 콘솔 사용 여부, 로컬에서 웹 브라우저로도 접속 가능
  datasource:
    url: jdbc:h2:mem:testdb # DB 접속 URL
    username: sa # DB 접속 username
    password: # DB 접속 password, 없음
    driver-class-name: org.h2.Driver # DB 접속 드라이버
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: qkrtngusxxx116.1234@gmail.com
            client-secret: abc7562571@
            scope: email
          naver:
            client-id: qkrtngus116
            client-secret: b7562571
            redirect-uri: http://localhost/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/vi/nid/me
            user-name-attribute: response


